Multiwoven/multiwoven-integrations

- .github/ISSUE_TEMPLATE/bug_report_template.md
- .github/ISSUE_TEMPLATE/documentation_update_template.md
- .github/ISSUE_TEMPLATE/feature_request_template.md
- .github/ISSUE_TEMPLATE/new_connector_issue_template.md
- .github/pull_request_template.md
---
name: Pull Request & Issues Template
title: GitHub PR & Issues Template
labels: ''
assignees: @karthik-sivadas
---
This pull request introduces updated GitHub Issues and Pull Request templates for the Multiwoven integrations gem. The update includes separate templates for different types of issues (bug reports, feature requests, documentation updates, etc.) and an enhanced PR template. These templates are designed to improve the clarity, consistency, and comprehensiveness of contributions and discussions within the project.
This PR is not linked to a specific issue but is part of ongoing improvements to project management and contribution processes.
Viewed the changes in Mark Down format viewer.
> Add github template for PR and issues

- .github/pull_request_template.md
- Gemfile.lock
- lib/multiwoven/integrations/destination/slack/config/catalog.json
- lib/multiwoven/integrations/rollout.rb
- multiwoven-integrations.gemspec
---
title: "[Chore]:  Add gem spec dependency"
labels: ''
assignees: ''
---
- [chore: Add gemspec dependency](https://github.com/Multiwoven/multiwoven-integrations/commit/ecb22433ef9544766246cea1ef786d6636d04c2b)
- [Updated the PR checklist](https://github.com/Multiwoven/multiwoven-integrations/commit/66355b7f4134e52e01c6425fe6b452a4d888392d)
None
> [Chore]: Add gemspec dependency, Update the PR checklist

- Gemfile.lock
- lib/multiwoven/integrations/destination/slack/client.rb
- lib/multiwoven/integrations/rollout.rb
- spec/multiwoven/integrations/destination/slack/client_spec.rb
---
title: "[Fix]: Update the sync_config based on Integration protocol" # e.g. Enhance Salesforce Connector Performance
labels: ''
assignees: @karthik-sivadas 
---
Update the sync_config based on the Integration protocol
None
> [Fix]: Update the sync_config based on Integration protocol

- lib/multiwoven/integrations/core/utils.rb
- lib/multiwoven/integrations/destination/salesforce_crm/client.rb
- lib/multiwoven/integrations/destination/slack/client.rb
- lib/multiwoven/integrations/destination/slack/config/spec.json
- spec/multiwoven/integrations/destination/salesforce_crm/client_spec.rb
- spec/multiwoven/integrations/destination/slack/client_spec.rb
---
title: "[Fix]: Update salesforce CRM based on sync config" # e.g. Enhance Salesforce Connector Performance
labels: ''
assignees: ''
---
- Update salesforce CRM based on sync config
- Update data attribute structure for slack and salesforce CRM
- None
Ran rspec
- [] Have you ensured that your changes for new connector are documented in the [docs repo](https://github.com/Multiwoven/docs) or relevant documentation files?
> Update salesforce CRM based on sync config

- Gemfile.lock
- lib/multiwoven/integrations/rollout.rb
- lib/multiwoven/integrations/source/redshift/config/spec.json
- lib/multiwoven/integrations/source/snowflake/config/spec.json
---
title: " Fix credentials structure update push in 0.1.8" # e.g. Enhance Salesforce Connector Performance
labels: ''
assignees: ''
---
Fix credentials structure update push in 0.1.8
None
> [Chore] Fix credentials structure update push in 0.1.8

- Gemfile.lock
- lib/multiwoven/integrations/core/base_connector.rb
- lib/multiwoven/integrations/core/constants.rb
- lib/multiwoven/integrations/destination/facebook_custom_audience/config/spec.json
- lib/multiwoven/integrations/destination/klaviyo/config/spec.json
- lib/multiwoven/integrations/destination/salesforce_crm/config/spec.json
- lib/multiwoven/integrations/destination/slack/config/spec.json
- lib/multiwoven/integrations/rollout.rb
- lib/multiwoven/integrations/service.rb
- lib/multiwoven/integrations/source/bigquery/client.rb
- lib/multiwoven/integrations/source/bigquery/config/spec.json
- lib/multiwoven/integrations/source/redshift/config/meta.json
- lib/multiwoven/integrations/source/redshift/config/spec.json
- lib/multiwoven/integrations/source/snowflake/config/spec.json
- spec/multiwoven/integrations/destination/salesforce_crm/client_spec.rb
- spec/multiwoven/integrations/source/bigquery/client_spec.rb
---
title: "[Fix] GitHub icon URL and big query contract" # e.g. Enhance Salesforce Connector Performance
labels: ''
assignees: ''
---
[[Fix] Biqquery spec and add description to other connector specs](https://github.com/Multiwoven/multiwoven-integrations/commit/970dd7ee5ffd3b339b2c0bc0459bb17bec7d3b93)
[[Fix] icon url serverd via meta_data](https://github.com/Multiwoven/multiwoven-integrations/commit/76fc2fa06b487316e3eb67711d6d16ee46df3343)
None
> [Fix] GitHub icon URL and big query contract

- Gemfile.lock
- lib/multiwoven/integrations/rollout.rb
- lib/multiwoven/integrations/source/redshift/config/meta.json
- spec/multiwoven/integrations/source/redshift/client_spec.rb
---
title: "[Fix] connector class name not matching meta.json name" # e.g. Enhance Salesforce Connector Performance
labels: ''
assignees: ''
---
[Fix] connector class name not matching meta.json name
None
- [] Added the new connector in rollout.rb
> [Fix] connector class name not matching meta.json name

- Gemfile.lock
- lib/multiwoven/integrations/core/base_connector.rb
- lib/multiwoven/integrations/rollout.rb
- spec/multiwoven/integrations/destination/salesforce_crm/client_spec.rb
- spec/multiwoven/integrations/source/redshift/client_spec.rb
---
title: "[Fix] icon url issue by placing it inside the data payload" # e.g. Enhance Salesforce Connector Performance
labels: ''
assignees: ''
---
[Fix] icon url issue by placing it inside the data payload. Currently it's being send outside the data
None
> [Fix] icon url issue by placing it inside the data payload

- lib/multiwoven/integrations/core/source_connector.rb
- lib/multiwoven/integrations/source/bigquery/client.rb
- lib/multiwoven/integrations/source/redshift/client.rb
- lib/multiwoven/integrations/source/snowflake/client.rb
- spec/multiwoven/integrations/source/bigquery/client_spec.rb
- spec/multiwoven/integrations/source/redshift/client_spec.rb
- spec/multiwoven/integrations/source/snowflake/client_spec.rb
---
title: "[TYPE]: Brief Description" # e.g. Enhance Salesforce Connector Performance
labels: ''
assignees: ''
---
> refactor: Extract querying logic to a method 

- .github/pull_request_template.md
- Gemfile.lock
- lib/multiwoven/integrations/rollout.rb
- lib/multiwoven/integrations/service.rb
- spec/multiwoven/integrations/service_spec.rb
[Fix] Update structure for build connector
None
> [Fix] Update structure for build connector

- Gemfile.lock
- lib/multiwoven/integrations/destination/facebook_custom_audience/client.rb
- lib/multiwoven/integrations/rollout.rb
- spec/multiwoven/integrations/destination/facebook_custom_audience/client_spec.rb
add batch support for facebook custom audience connector
> [feature]: add batch support for facebook custom audience connector

- README.md
> Add detailed readme 

- .github/workflows/release.yml
> feat: Publish gem to rubygems

- Gemfile.lock
- lib/multiwoven/integrations/protocol/protocol.rb
- lib/multiwoven/integrations/rollout.rb
> feat: Bump version to 1.21

- Gemfile.lock
- lib/multiwoven/integrations/destination/facebook_custom_audience/config/catalog.json
- lib/multiwoven/integrations/protocol/protocol.rb
- lib/multiwoven/integrations/rollout.rb
- spec/multiwoven/integrations/protocol/protocol_spec.rb
> [feat]: adding batch_support flag and batch_size in catalog for sync

- Gemfile.lock
- lib/multiwoven/integrations/destination/facebook_custom_audience/client.rb
- lib/multiwoven/integrations/rollout.rb
- spec/multiwoven/integrations/destination/facebook_custom_audience/client_spec.rb
> fix: discover method fix

- .github/workflows/release.yml
- Gemfile.lock
- lib/multiwoven/integrations/rollout.rb
fix: update the release GitHub action to use official gem release action
None
Have not tested
> fix: update the release GitHub action to use official gem release action

- Gemfile.lock
- lib/multiwoven/integrations/destination/facebook_custom_audience/client.rb
- lib/multiwoven/integrations/destination/facebook_custom_audience/config/meta.json
- lib/multiwoven/integrations/destination/klaviyo/config/meta.json
- lib/multiwoven/integrations/destination/salesforce_crm/config/meta.json
- lib/multiwoven/integrations/destination/slack/config/meta.json
- lib/multiwoven/integrations/rollout.rb
- lib/multiwoven/integrations/source/bigquery/config/meta.json
- lib/multiwoven/integrations/source/redshift/config/meta.json
- lib/multiwoven/integrations/source/snowflake/config/meta.json
- spec/multiwoven/integrations/rollout_spec.rb
feat: Add the title to all the meta JSON in all connector
None
Wrote unit tests for the implementation
> feat: Add title to all the meta json in all connector

- Gemfile.lock
- lib/multiwoven/integrations/core/rate_limiter.rb
- lib/multiwoven/integrations/core/utils.rb
- lib/multiwoven/integrations/destination/facebook_custom_audience/client.rb
- lib/multiwoven/integrations/destination/facebook_custom_audience/config/catalog.json
- lib/multiwoven/integrations/destination/klaviyo/client.rb
- lib/multiwoven/integrations/destination/klaviyo/config/catalog.json
- lib/multiwoven/integrations/destination/salesforce_crm/client.rb
- lib/multiwoven/integrations/destination/salesforce_crm/config/catalog.json
- lib/multiwoven/integrations/destination/slack/client.rb
- lib/multiwoven/integrations/destination/slack/config/catalog.json
- lib/multiwoven/integrations/protocol/protocol.rb
- lib/multiwoven/integrations/rollout.rb
- lib/multiwoven/integrations/service.rb
- spec/multiwoven/integrations/core/rate_limiter_spec.rb
- spec/multiwoven/integrations/destination/facebook_custom_audience/client_spec.rb
- spec/multiwoven/integrations/destination/klaviyo/client_spec.rb
- spec/multiwoven/integrations/destination/salesforce_crm/client_spec.rb
- spec/multiwoven/integrations/destination/slack/client_spec.rb
- spec/multiwoven/integrations/service_spec.rb
- spec/spec_helper.rb
> feat: configure rate limit for destinations

- .gitignore
- Gemfile.lock
- lib/multiwoven/integrations.rb
- lib/multiwoven/integrations/core/constants.rb
- lib/multiwoven/integrations/rollout.rb
- lib/multiwoven/integrations/source/databricks/client.rb
- lib/multiwoven/integrations/source/databricks/config/meta.json
- lib/multiwoven/integrations/source/databricks/config/spec.json
- lib/multiwoven/integrations/source/databricks/icon.svg
- spec/multiwoven/integrations/source/databricks/client_spec.rb
> feat: source/databricks

- Gemfile.lock
- lib/multiwoven/integrations/rollout.rb
- lib/multiwoven/integrations/source/databricks/config/spec.json
> fix: databricks connector specification 

- .gitignore
- Gemfile.lock
- lib/multiwoven/integrations/core/utils.rb
- lib/multiwoven/integrations/destination/hubspot/config/catalog.json
- lib/multiwoven/integrations/destination/klaviyo/config/catalog.json
- lib/multiwoven/integrations/destination/salesforce_crm/config/catalog.json
- lib/multiwoven/integrations/destination/slack/config/catalog.json
- lib/multiwoven/integrations/protocol/protocol.rb
- lib/multiwoven/integrations/rollout.rb
- spec/multiwoven/integrations/destination/facebook_custom_audience/client_spec.rb
- spec/multiwoven/integrations/destination/hubspot/client_spec.rb
- spec/multiwoven/integrations/destination/klaviyo/client_spec.rb
- spec/multiwoven/integrations/destination/salesforce_crm/client_spec.rb
- spec/multiwoven/integrations/destination/slack/client_spec.rb
- spec/multiwoven/integrations/protocol/protocol_spec.rb
> feat: sync mode changes for destination connectors

- Gemfile.lock
- lib/multiwoven/integrations/rollout.rb
fix: update gem version
None
build it locally
> fix: update gem version

- Gemfile.lock
- lib/multiwoven/integrations/rollout.rb
- lib/multiwoven/integrations/source/salesforce_consumer_goods_cloud/config/spec.json
> fix: Spec password

- Gemfile.lock
- lib/multiwoven/integrations/rollout.rb
- lib/multiwoven/integrations/source/salesforce_consumer_goods_cloud/client.rb
- spec/multiwoven/integrations/source/salesforce_consumer_goods/client_spec.rb
fix: Update the query and create connection
None
Tested by using this branch in server and making API call
> fix: Update query and create connection

- Gemfile.lock
- lib/multiwoven/integrations/core/utils.rb
- lib/multiwoven/integrations/destination/sftp/client.rb
- lib/multiwoven/integrations/destination/sftp/config/catalog.json
- lib/multiwoven/integrations/protocol/protocol.rb
- lib/multiwoven/integrations/rollout.rb
- lib/multiwoven/integrations/source/salesforce_consumer_goods_cloud/client.rb
- spec/multiwoven/integrations/destination/sftp/client_spec.rb
- spec/multiwoven/integrations/protocol/protocol_spec.rb
> fix: sftp server integration

- Gemfile.lock
- lib/multiwoven/integrations/destination/sftp/client.rb
- lib/multiwoven/integrations/rollout.rb
- spec/multiwoven/integrations/destination/sftp/client_spec.rb
> fix: sftp full refresh

- Gemfile.lock
- lib/multiwoven/integrations/destination/postgresql/config/meta.json
- lib/multiwoven/integrations/rollout.rb
> Enable postgres destination

- Gemfile.lock
- lib/multiwoven/integrations/rollout.rb
chore: Update gem version
None
Nope
> chore: Update gem version

- Gemfile.lock
- lib/multiwoven/integrations/destination/sftp/client.rb
- lib/multiwoven/integrations/destination/sftp/config/catalog.json
- lib/multiwoven/integrations/rollout.rb
> fix: destination path fix in check connection
